site_name: Formatting Guide
repo_url: 'https://github.com/frogweezer/formatting'
repo_name: frogweezer/formatting
copyright: Copyright &copy; 2021 frogweezer
theme:
  name: null
  custom_dir: mkdocs-material/material
  logo: assets/icon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: black
    accent: indigo
  features:
    - navigation.tabs

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico

nav:
  - Home: index.md
  - Markdown:
    - Introduction: markdown/index.md
    - Lists: markdown/lists.md
    - Images: markdown/images.md
    - Code: markdown/code.md
    - Quotes: markdown/quotes.md
    - Tables: markdown/tables.md
    - HTML: markdown/html.md
    - Advanced Tricks: markdown/advanced.md
  - About:
    - Project: about/index.md
    - Changelog: about/changelog.md
    - Contributing: about/contributing.md
    - Source: about/source.md

extra:
  social:
    - icon: fontawesome/brands/git-alt
      link: https://github.com/frogweezer
    - icon: fontawesome/brands/github
      link: https://github.com/frogweezer/formatting
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Dream_Lanterns
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCtbA8YpCwcAGKJUHRxMclIg
    - icon: fontawesome/brands/discord
      link: https://discord.gg/KUTsuzZWwD
  #disqus: formatting-guide
  generator: false
