site_name: Formatting Guide
repo_url: 'https://github.com/sleepiie/formatting'
repo_name: sleepiie/formatting
theme:
  name: null
  custom_dir: mkdocs-material/material
  logo: icon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: black
    accent: indigo
  features:
    - navigation.tabs

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: favicon.ico
